### ISSUE TITLE
Restrict network management to only display network variables

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#13]
Currently the file displayed in Network Management is the appliance `vars.sh` file which sets up most of the variables for the system. This includes VPN information and the root password which admins should not be able to see or modify.

Can we set the network management screen to only display `alces_INTERNAL_*` and `alces_EXTERNAL_*` variables?

**Comment by atoghill** [comment]
Yep! I wasn't sure which variables we were wanting to allow modifications for originally. Should be easy enough to restrict this 😃
