### ISSUE TITLE
Machine management tools prompts to save a file?

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#14]
When clicking `restart` from the GUI it seems to prompt to save a file called `restart`.

<img width="883" alt="screenshot 2019-02-25 at 15 27 26" src="https://user-images.githubusercontent.com/27725639/53347923-035afd00-3912-11e9-9e08-e6c76c5bce65.png">
<img width="1084" alt="screenshot 2019-02-25 at 15 27 38" src="https://user-images.githubusercontent.com/27725639/53347929-06ee8400-3912-11e9-934b-edeab185ec7a.png">
<img width="222" alt="screenshot 2019-02-25 at 15 28 11" src="https://user-images.githubusercontent.com/27725639/53347944-0c4bce80-3912-11e9-8fdf-31efe2f177b6.png">

It does restart the machine properly though!

**Comment by ColonelPanicks** [comment]
This issue only seems to occur on Chrome, Firefox didn't have the same issue.

**Comment by atoghill** [comment]
If this is Chrome attempting to be clever then it could be interesting to fix 🤔
