### ISSUE TITLE
Global Script Configuration

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#29]
Provide a configuration method for an entrypoint script and argument configuration in order to reduce the amount of system stuff that Overware has hard-coded into it.

My thinking is that the configuration would be something like:
```
ENTRYPOINT="/appliance/scripts/action.sh"
VPN_START="vpn start"
VPN_STOP="vpn stop"
VPN_RESTART="vpn restart"
NETWORK_SET="network set"
```
While there is most likely going to be a level of consistency/stability to the arguments provided, adding these in configuration will reduce the hard-coding of system commands/arguments inside Overware itself.

That's my 2c, I'm open to ideas and alternatives.

Reference - https://github.com/alces-software/appliance-configuration/issues/13

## Dependent Issues

The following issues involve interacting with appliance configuration module scripts and therefore are dependent on how the global configuration is approached:
- #24 
- #26 
- #27

**Comment by ColonelPanicks** [comment]
An action helper script and the various overware functions have been split out into module scripts.

Documentation on them can be found at https://github.com/alces-software/appliance-configuration#running-customisations

**Comment by atoghill** [comment]
Closing this now that we have had some time to play with it.
