### ISSUE TITLE
[Bolt-On] VPN Tool

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#6]
`[Bolt-On]` implies that this feature is an optional part of the web interface configuration.

This page will be used for managing the VPN connection, namely:
- Start VPN (`systemctl start openvpn@flightcenter`)
- Stop VPN (`systemctl stop openvpn@flightcenter`)
- Restart VPN (`systemctl restart openvpn@flightcenter`)

**Comment by ColonelPanicks** [comment]
Tested on 1.1rc1 and all works as expected!

**Comment by atoghill** [comment]
Closing this issue now that things have been tested
