### ISSUE TITLE
Editing of Variables

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#7]
The appliance configuration process (https://github.com/alces-software/appliance-configuration) uses a variable file to configure the name, passwords and role of the appliance running Overware.

Part of this variable script includes network configuration options, being able to update the variables in `/appliance/scripts/vars.sh` through the web interface would allow for web-based reconfiguration of the networks (when the setup script is run again with `alces_RERUN=true bash /appliance/scripts/personality_base.sh`)

**Comment by ColonelPanicks** [comment]
@atoghill it doesn't look like the command `alces_RERUN=true bash /appliance/scripts/personality_base.sh` is run after settings have been saved.

**Comment by atoghill** [comment]
As discussed IRL I didn't realise this was something we wanted but in hindsight can see that it would be useful. Working on this now, shouldn't take too long to implement and then I will release `1.1rc3` to address this.

**Comment by atoghill** [comment]
Closing now that `1.1` has been released.
